name: VideoGamesLifeServer
version: '${project.version}'
main: org.scarlettparker.videogameslifeserver.Main
api-version: '1.20'
author: Scarlett Parker

commands:
  givelife:
    description: Give a life to a player.
    usage: /<command> player
  startlife:
    description: Starts the life server.
    usage: /<command> lives
  setlife:
    description: Updates a player's lives.
    usage: /<command> player lives
  addtask:
    description: Adds a new task.
    usage: /<command>
  completetask:
    description: Completes a user's task.
    usage: /<command> player
  deletetask:
    description: Deletes a task.
    usage: /<command> taskID
  excludetask:
    description: Excludes a task.
    usage: /<command> taskID
  failtask:
    description: Fails a user's task.
    usage: /<command> player
  listtasks:
    description: Lists all (non-excluded) tasks.
    usage: /<command> [allowed|excluded]
  newtask:
    description: Gives a player a new task.
    usage: /<command> normal|hard player
  sessiontasks:
    description: Initializes the tasks for the session.
    usage: /<command>
  settask:
    description: Sets a player's task.
    usage: /<command> player taskID
  starttasks:
    description: Initializes the tasks.
    usage: /<command>
  whattask:
    description: Displays the player's current task.
    usage: /<command>
  tokens:
    description: Displays current number of tokens.
    usage: /<command>
  givetokens:
    description: Gives a player a number of tokens.
    usage: /<command> player tokens
  settokens:
    description: Sets a player's tokens.
    usage: /<command> player tokens
  shop:
    description: Displays the token shop.
    usage: /<command>
  clearpunishments:
    description: Clears a player's punishments.
    usage: /<command> player
  setpunishment:
    description: Adds a punishment to a player.
    usage: /<command> player punishmentID