name: VideoGamesLifeServer
version: '${project.version}'
main: org.scarlettparker.videogameslifeserver.Main
api-version: '1.20'
author: Scarlett Parker

commands:
  givelife:
    description: Give a life to a player.
    usage: /<command> player
  startlife:
    description: Starts the life server.
    usage: /<command> lives
  setlife:
    description: Updates a player's lives.
    usage: /<command> player lives
  addtask:
    description: Adds a new task.
    usage: /<command>
  cleartask:
    description: Clears a player's task
    usage: /<command> player
  completetask:
    description: Completes a player's task.
    usage: /<command> player
  deletetask:
    description: Deletes a task.
    usage: /<command> taskID
  edittask:
    description: Edits a task by its name.
    usage: /<command>
  excludeplayer:
    description: Excludes a player from a task.
    usage: /<command> taskID player
  excludetask:
    description: Excludes a task.
    usage: /<command> taskID
  failtask:
    description: Fails a user's task.
    usage: /<command> player
  forcetask:
    description: Force a player's next task.
    usage: /<command> player taskID
  listtasks:
    description: Lists all (non-excluded) tasks.
    usage: /<command> [allowed|excluded]
  newtask:
    description: Gives a player a new task.
    usage: /<command> normal|hard player
  setpriority:
    description: Set a task's priority.
    usage: /<command> taskID priority
  settask:
    description: Sets a player's task.
    usage: /<command> player taskID
  starttasks:
    description: Initializes the tasks.
    usage: /<command>
  whattask:
    description: Displays the player's current task.
    usage: /<command>
  tokens:
    description: Displays current number of tokens.
    usage: /<command>
  gift:
    description: Gift a player a number of tokens.
    usage: /<command> player tokens
  settokens:
    description: Sets a player's tokens.
    usage: /<command> player tokens
  shop:
    description: Displays the token shop.
    usage: /<command>
  setvillagershop:
    description: Sets up the villager shop.
    usage: /<command>
  clearpunishments:
    description: Clears a player's punishments.
    usage: /<command> player
  setpunishment:
    description: Adds a punishment to a player.
    usage: /<command> player punishmentID